sudo: required
language: minimal
python: 3.5

services:
  - docker

env:
  - TOX_ENV=py35

git:
  submodules: false

before_install:
  - set -e
  - rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
  - sudo rm -rf /usr/local/clang*
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  # As Travis VM is limited to 30Go, we remove all conda envs once they are installed successfully to free some disk space (see #23)
  - sed -i 's|\(install-tools.*&&\) \\|\1 rm \-rf /tool_deps/_conda/envs/* \&\& \\|g' Dockerfile
  - make docker_install
  # Next line is an alternative to travis_wait that allows to keep the logs from make docker_build
  - while sleep 9m; do echo "[TRAVIS] Still running..."; done &
  - make docker_build
  - make docker_run
  - sleep 300

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - make test_bioblend
  #- make test_docker_in_docker
